name: kintsugi
description: An application for demonstrating better accessibility features.
version: 1.1.1+7
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  provider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  speech_recognition: ^0.3.0+1
  flutter_audio_recorder2: ^0.0.2
  path_provider: ^2.0.11
  flip_card: ^0.4.4
  url_launcher: ^6.0.6
  flutter_speech: ^2.0.0
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/core/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/core/
