name: kintsugi
description: An application for demonstrating better accessibility features.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  speech_recognition: ^0.3.0+1
  flutter_audio_recorder2: ^0.0.2
  path_provider: ^1.5.1
  flip_card: ^0.4.4
  noise_meter: ^3.0.0
  syncfusion_flutter_charts: ^19.1.67
  url_launcher: ^6.0.6
  flutter_speech: ^2.0.0
  #  permission_handler: ^7.0.0
  #  flutter_sound_lite: ^8.1.9
  #  audio_streamer: ^1.1.6
  #  audioplayers:  ^0.16.0
  #  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
