// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSq5DqOdcK2JcuZrx4rOkc0L3vmTmVsg0',
    appId: '1:933872441863:web:96db0b0e4634d4f84828a2',
    messagingSenderId: '933872441863',
    projectId: 'accesstant',
    authDomain: 'accesstant.firebaseapp.com',
    storageBucket: 'accesstant.appspot.com',
    measurementId: 'G-8SEDKL82DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhd9YJvCGkmH8mslUMj_ayGEcxeRPDIyA',
    appId: '1:933872441863:android:3e2fb8e43b9637824828a2',
    messagingSenderId: '933872441863',
    projectId: 'accesstant',
    storageBucket: 'accesstant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QELksJYwMEjkehfixK8uGnMgOR5fRBA',
    appId: '1:933872441863:ios:44031fb7462930eb4828a2',
    messagingSenderId: '933872441863',
    projectId: 'accesstant',
    storageBucket: 'accesstant.appspot.com',
    iosClientId: '933872441863-k4k8u0fdcgb5caq7cad3t67ofom70thb.apps.googleusercontent.com',
    iosBundleId: 'com.vohoangphuc.kintsugi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QELksJYwMEjkehfixK8uGnMgOR5fRBA',
    appId: '1:933872441863:ios:44031fb7462930eb4828a2',
    messagingSenderId: '933872441863',
    projectId: 'accesstant',
    storageBucket: 'accesstant.appspot.com',
    iosClientId: '933872441863-k4k8u0fdcgb5caq7cad3t67ofom70thb.apps.googleusercontent.com',
    iosBundleId: 'com.vohoangphuc.kintsugi',
  );
}
